# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-08-10 02:15
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=200)),
                ('text', models.TextField()),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('approved_comment', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='CuestionarioDelphi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('estado', models.BooleanField(default=True)),
                ('fecha_inicio', models.DateField(default=django.utils.timezone.now)),
                ('fecha_final', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='EstudioDelphi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proyecto', models.CharField(max_length=100)),
                ('titulo', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
                ('objetivos', models.TextField()),
                ('fecha_inicio', models.DateField(default=django.utils.timezone.now)),
                ('fecha_final', models.DateField(default=django.utils.timezone.now)),
                ('estado', models.BooleanField(default=True)),
                ('coordinadores', models.ManyToManyField(related_name='coordinadores', to=settings.AUTH_USER_MODEL, verbose_name='coordinadores')),
                ('moderador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delphi_moderador', to=settings.AUTH_USER_MODEL, verbose_name='moderador')),
                ('participantes', models.ManyToManyField(related_name='participantes', to=settings.AUTH_USER_MODEL, verbose_name='participantes')),
            ],
            options={
                'verbose_name': 'Estudio Delphi',
                'verbose_name_plural': 'Estudios Delphi',
            },
        ),
        migrations.CreateModel(
            name='OpcionRespuesta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto_opcion', models.CharField(max_length=200)),
                ('valor_inicio', models.IntegerField(default=0)),
                ('valor_final', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Opcion',
                'verbose_name_plural': 'Opciones',
            },
        ),
        migrations.CreateModel(
            name='Pregunta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_pregunta', models.CharField(choices=[('unica', 'Selección única'), ('multi', 'Selección múltiple'), ('texto', 'Abierta'), ('escala', 'Escala Likert'), ('numerica', 'Escala númerica'), ('ranking', 'Ranking')], max_length=10)),
                ('enunciado_pregunta', models.TextField()),
                ('de_control', models.BooleanField(default=False)),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='autor', to=settings.AUTH_USER_MODEL, verbose_name='autor')),
                ('cuestionario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='delphi.CuestionarioDelphi')),
            ],
            options={
                'verbose_name': 'Pregunta',
                'verbose_name_plural': 'Preguntas',
            },
        ),
        migrations.CreateModel(
            name='RespuestasUsuarios',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('respuesta_texto', models.TextField(blank=True, null=True)),
                ('respuesta_numerica', models.IntegerField(default=0)),
                ('fecha', models.DateTimeField(default=django.utils.timezone.now)),
                ('opciones_seleccionadas', models.ManyToManyField(to='delphi.OpcionRespuesta')),
                ('pregunta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='delphi.Pregunta')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RondasDelphi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_ronda', models.IntegerField()),
                ('descripcion', models.TextField()),
                ('abierto', models.BooleanField(default=True, help_text='Dice si se pueden votar o no las preguntas.')),
                ('numero_preguntas', models.IntegerField(default=1)),
                ('fecha_inicio', models.DateField(default=django.utils.timezone.now)),
                ('fecha_final', models.DateField(default=django.utils.timezone.now)),
                ('cuestionario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='delphi.CuestionarioDelphi', verbose_name='Cuestionario')),
                ('delphi', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ronda_delphi', to='delphi.EstudioDelphi')),
            ],
            options={
                'verbose_name': 'Ronda',
                'verbose_name_plural': 'Rondas',
            },
        ),
        migrations.CreateModel(
            name='SesionCuestionario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_sesion', models.IntegerField()),
                ('nombre', models.CharField(max_length=100)),
                ('permitir_preguntas', models.BooleanField(default=False, help_text='Dice si se pueden crear preguntas o no. y si esta desactivado se pueden votar por las preguntas ya creadas')),
                ('estado', models.BooleanField(default=True, help_text='Dice si se pueden votar o no.')),
                ('fecha', models.DateTimeField(default=django.utils.timezone.now)),
                ('fecha_inicio', models.DateField(default=django.utils.timezone.now)),
                ('fecha_final', models.DateField(default=django.utils.timezone.now)),
                ('cuestionario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='delphi.CuestionarioDelphi', verbose_name='cuestionario_delphi')),
            ],
            options={
                'verbose_name': 'Sesion cuestionario Delphi',
                'verbose_name_plural': 'Sesiones de cuestionario Delphi',
                'ordering': ('cuestionario', 'codigo_sesion'),
            },
        ),
        migrations.AddField(
            model_name='pregunta',
            name='sesion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='delphi.SesionCuestionario'),
        ),
        migrations.AddField(
            model_name='pregunta',
            name='votos_negativos',
            field=models.ManyToManyField(blank=True, related_name='votos_negativos', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='pregunta',
            name='votos_positivos',
            field=models.ManyToManyField(blank=True, related_name='votos_positivos', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='opcionrespuesta',
            name='pregunta',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='delphi.Pregunta'),
        ),
        migrations.AddField(
            model_name='cuestionariodelphi',
            name='delphi',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cuestionario_delphi', to='delphi.EstudioDelphi'),
        ),
        migrations.AddField(
            model_name='comment',
            name='pregunta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='delphi.Pregunta'),
        ),
        migrations.AlterUniqueTogether(
            name='sesioncuestionario',
            unique_together=set([('codigo_sesion', 'cuestionario')]),
        ),
        migrations.AlterUniqueTogether(
            name='rondasdelphi',
            unique_together=set([('numero_ronda', 'cuestionario')]),
        ),
        migrations.AlterUniqueTogether(
            name='respuestasusuarios',
            unique_together=set([('pregunta', 'usuario')]),
        ),
        migrations.AlterUniqueTogether(
            name='opcionrespuesta',
            unique_together=set([('texto_opcion', 'pregunta', 'valor_inicio', 'valor_final')]),
        ),
    ]
