# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-08-03 18:09
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EstudioMicmac',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proyecto', models.CharField(max_length=100)),
                ('titulo', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
                ('objetivos', models.TextField()),
                ('fecha_inicio', models.DateField(default=django.utils.timezone.now)),
                ('fecha_final', models.DateField(default=django.utils.timezone.now)),
                ('estado', models.BooleanField(default=True)),
                ('coordinadores', models.ManyToManyField(related_name='micmac_coordinadores', to=settings.AUTH_USER_MODEL, verbose_name='coordinadores')),
                ('expertos', models.ManyToManyField(related_name='micmac_expertos', to=settings.AUTH_USER_MODEL, verbose_name='expertos')),
                ('moderador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='micmac_moderador', to=settings.AUTH_USER_MODEL, verbose_name='moderador')),
            ],
            options={
                'verbose_name': 'Estudio Micmac',
                'verbose_name_plural': 'Estudios Micmac',
            },
        ),
        migrations.CreateModel(
            name='Relacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valoracion', models.IntegerField(choices=[(0, 'NULA'), (1, 'DÉBIL'), (2, 'MODERADA'), (3, 'FUERTE'), (4, 'POTENCIAL')])),
                ('descripcion', models.TextField(default='')),
            ],
        ),
        migrations.CreateModel(
            name='SesionVariables',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('codigo', models.PositiveIntegerField()),
                ('estado', models.BooleanField(default=True, help_text='Dice si se pueden votar o no.')),
                ('fecha_inicio', models.DateField(default=django.utils.timezone.now)),
                ('fecha_final', models.DateField(default=django.utils.timezone.now)),
                ('estudio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='micmac.EstudioMicmac', verbose_name='estudio_micmac')),
            ],
            options={
                'verbose_name': 'Sesion de creacion de variables Micmac',
                'verbose_name_plural': 'Sesiones de creacion de variables',
                'ordering': ('estudio', 'codigo'),
            },
        ),
        migrations.CreateModel(
            name='Variable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=500)),
                ('nombre_corto', models.CharField(max_length=10)),
                ('descripcion', models.TextField()),
                ('total_influencia', models.PositiveIntegerField(default=0)),
                ('total_dependencia', models.PositiveIntegerField(default=0)),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='autor_variable', to=settings.AUTH_USER_MODEL, verbose_name='autor')),
                ('estudio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='micmac.EstudioMicmac')),
                ('relacion', models.ManyToManyField(through='micmac.Relacion', to='micmac.Variable')),
                ('votos_negativos', models.ManyToManyField(default=None, related_name='votante_negativo_variable', to=settings.AUTH_USER_MODEL, verbose_name='votante_negativo')),
                ('votos_positivos', models.ManyToManyField(default=None, related_name='votante_positivo_variable', to=settings.AUTH_USER_MODEL, verbose_name='votante_positivo')),
            ],
            options={
                'verbose_name': 'Variable',
                'verbose_name_plural': 'Variables',
            },
        ),
        migrations.AddField(
            model_name='relacion',
            name='a_variable',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='a_variable', to='micmac.Variable'),
        ),
        migrations.AddField(
            model_name='relacion',
            name='de_variable',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='de_variable', to='micmac.Variable'),
        ),
        migrations.AlterUniqueTogether(
            name='sesionvariables',
            unique_together=set([('codigo', 'estudio')]),
        ),
        migrations.AlterUniqueTogether(
            name='relacion',
            unique_together=set([('de_variable', 'a_variable')]),
        ),
    ]
